name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # =========================
    # SYSTEM DEPENDENCIES
    # =========================
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip wget openjdk-17-jdk python3-pip \
        autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
        libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev

    # =========================
    # PYTHON DEPENDENCIES
    # =========================
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    # =========================
    # CLEAN CACHE
    # =========================
    - name: Clean Buildozer cache
      run: |
        rm -rf ~/.buildozer

    # =========================
    # BUILD APK
    # =========================
    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk

        buildozer -v android debug
